import { Router } from "express";
import { authenticate, authorize } from "../middleware/authenticate.js";
import { customerMutationLimiter } from "../middleware/rateLimiter.js";
import { USER_ROLES } from "../utils/constants.js";
import { getServicePolicy, createCustomerServiceRequest, listCustomerServiceRequests, getCustomerServiceRequest, listCustomerServiceQuotes, getCustomerServiceQuote, decideCustomerServiceQuote, recordStaffAssessment, createStaffServiceQuotation, listCustomerServiceHistory, getCustomerServiceHistory } from "../controllers/customerServicesController.js";
const router = Router();
router.get("/policy", authenticate, getServicePolicy);
router.post("/requests", authenticate, customerMutationLimiter, createCustomerServiceRequest);
router.get("/requests/mine", authenticate, listCustomerServiceRequests);
router.get("/requests/:id", authenticate, getCustomerServiceRequest);
router.get("/requests/:id/assessment", authenticate, getCustomerServiceRequest);
router.get("/requests/:id/quotations", authenticate, listCustomerServiceQuotes);
router.patch("/requests/:id/assessment", authenticate, authorize(USER_ROLES.TECHNICIAN, USER_ROLES.SALES_ADVISOR, USER_ROLES.OPS_MANAGER, USER_ROLES.SUPER_ADMIN), recordStaffAssessment);
router.post("/requests/:id/quotations", authenticate, authorize(USER_ROLES.SALES_ADVISOR, USER_ROLES.OPS_MANAGER, USER_ROLES.SUPER_ADMIN), createStaffServiceQuotation);
router.get("/quotations/:id", authenticate, getCustomerServiceQuote);
router.post("/quotations/:id/approve", authenticate, customerMutationLimiter, decideCustomerServiceQuote("approve"));
router.post("/quotations/:id/decline", authenticate, customerMutationLimiter, decideCustomerServiceQuote("decline"));
router.get("/history", authenticate, listCustomerServiceHistory);
router.get("/history/:id", authenticate, getCustomerServiceHistory);
export default router;
