import { Router } from "express";
import { authenticate, authorize } from "../middleware/authenticate.js";
import { customerMutationLimiter } from "../middleware/rateLimiter.js";
import { USER_ROLES } from "../utils/constants.js";
import { createSupplier, createPurchaseOrder, approvePurchaseOrder, receivePurchaseOrder } from "../controllers/procurementController.js";
import { createCustomerProcurementRequest, listCustomerProcurementRequests, getCustomerProcurementRequest, patchCustomerProcurementRequest, respondCustomerProcurementClarification, listCustomerProcurementQuotations, getCustomerProcurementQuotation, decideCustomerProcurementQuotation, createStaffCustomerProcurementQuotation } from "../controllers/procurementCustomerController.js";
const router = Router();
const manage = [USER_ROLES.INVENTORY_OFFICER, USER_ROLES.OPS_MANAGER, USER_ROLES.SUPER_ADMIN];
router.post("/suppliers", authenticate, authorize(...manage), createSupplier);
router.post("/purchase-orders", authenticate, authorize(...manage), createPurchaseOrder);
router.post("/purchase-orders/:id/approve", authenticate, authorize(USER_ROLES.OPS_MANAGER, USER_ROLES.SUPER_ADMIN), approvePurchaseOrder);
router.post("/purchase-orders/:id/receipts", authenticate, authorize(...manage), receivePurchaseOrder);
router.post("/requests", authenticate, customerMutationLimiter, createCustomerProcurementRequest);
router.get("/requests/mine", authenticate, listCustomerProcurementRequests);
router.get("/requests/:id", authenticate, getCustomerProcurementRequest);
router.patch("/requests/:id", authenticate, customerMutationLimiter, patchCustomerProcurementRequest);
router.post("/requests/:id/clarifications/:clarificationId", authenticate, customerMutationLimiter, respondCustomerProcurementClarification);
router.get("/requests/:id/quotations", authenticate, listCustomerProcurementQuotations);
router.post("/requests/:id/quotations", authenticate, authorize(USER_ROLES.SALES_ADVISOR, USER_ROLES.OPS_MANAGER, USER_ROLES.SUPER_ADMIN), createStaffCustomerProcurementQuotation);
router.get("/quotations/:id", authenticate, getCustomerProcurementQuotation);
router.post("/quotations/:id/approve", authenticate, customerMutationLimiter, decideCustomerProcurementQuotation("approve"));
router.post("/quotations/:id/decline", authenticate, customerMutationLimiter, decideCustomerProcurementQuotation("decline"));
export default router;
