import { Router } from "express";
import { authenticate, authorize } from "../middleware/authenticate.js";
import { USER_ROLES } from "../utils/constants.js";
import { customerMutationLimiter } from "../middleware/rateLimiter.js";
import { createReturn, listMyReturns, decideReturn, getReturnDetail, getReturnEligibility } from "../controllers/returnController.js";
const router = Router();
router.get("/orders/:orderId/eligibility", authenticate, getReturnEligibility);
router.post("/orders/:orderId", authenticate, customerMutationLimiter, createReturn);
router.get("/mine", authenticate, listMyReturns);
router.get("/:id", authenticate, getReturnDetail);
router.patch("/:id/decision", authenticate, authorize(USER_ROLES.SUPPORT_OFFICER, USER_ROLES.FINANCE_OFFICER, USER_ROLES.OPS_MANAGER, USER_ROLES.SUPER_ADMIN), decideReturn);
export default router;
