import { Router } from "express";
import { authenticate, authorize } from "../middleware/authenticate.js";
import { customerMutationLimiter } from "../middleware/rateLimiter.js";
import { createSupportTicket, replyToTicket, updateTicketStatus, getMyTickets, getTicketDetail } from "../controllers/supportTicketController.js";
import { USER_ROLES } from "../utils/constants.js";
const router = Router();
router.get("/mine", authenticate, getMyTickets);
router.post("/", authenticate, customerMutationLimiter, createSupportTicket);
router.get("/:id", authenticate, getTicketDetail);
router.post("/:id/reply", authenticate, customerMutationLimiter, replyToTicket);
router.patch("/:id/status", authenticate, authorize(USER_ROLES.SUPPORT_OFFICER, USER_ROLES.OPS_MANAGER, USER_ROLES.SUPER_ADMIN), updateTicketStatus);
export default router;
