import swaggerJSDoc from "swagger-jsdoc";

const options = {
  definition: {
    openapi: "3.1.0",
    info: {
      title: "Sanfaani Store & Repair API",
      version: "1.0.0",
      description: "API documentation for the Sanfaani Store & Repair platform",
    },
    servers: [
      { url: "http://localhost:5000/api", description: "Local development" },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
        repairTrackingToken: {
          type: "apiKey",
          in: "header",
          name: "X-Repair-Tracking-Token",
          description:
            "Opaque, read-only repair tracking credential. It is not accepted by mutation endpoints.",
        },
        guidanceResumeToken: {
          type: "apiKey",
          in: "header",
          name: "X-Guidance-Resume-Token",
          description: "Opaque guest guidance session resume credential.",
        },
      },
      schemas: {
        StandardError: {
          type: "object",
          required: ["success", "message", "errors"],
          additionalProperties: false,
          properties: {
            success: { type: "boolean", const: false },
            message: { type: "string" },
            errors: {
              type: "array",
              items: {
                type: "object",
                required: ["code", "message"],
                properties: {
                  field: { type: "string" },
                  code: { type: "string" },
                  message: { type: "string" },
                },
              },
            },
          },
        },
        Pagination: {
          type: "object",
          required: ["page", "limit", "total", "pages", "hasNextPage"],
          additionalProperties: false,
          properties: {
            page: { type: "integer", minimum: 1 },
            limit: { type: "integer", minimum: 1 },
            total: { type: "integer", minimum: 0 },
            pages: { type: "integer", minimum: 0 },
            hasNextPage: { type: "boolean" },
          },
        },
        InternalSupplier: {
          type: "object",
          additionalProperties: false,
          required: ["id", "name", "email", "phone", "active", "version", "deactivatedAt", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            email: { type: ["string", "null"], format: "email" },
            phone: { type: ["string", "null"] },
            active: { type: "boolean" },
            version: { type: "integer", minimum: 0 },
            deactivatedAt: { type: ["string", "null"], format: "date-time" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        InternalPurchaseOrder: {
          type: "object",
          additionalProperties: false,
          required: ["id", "supplierId", "status", "version", "lines", "evidenceIds", "receipts", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            supplierId: { type: "string" },
            status: { type: "string", enum: ["DRAFT", "PENDING_APPROVAL", "APPROVED", "RECEIVING", "CLOSED", "CANCELLED"] },
            version: { type: "integer", minimum: 0 },
            lines: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                required: ["variantId", "quantity", "unitCost", "receivedQuantity"],
                properties: {
                  variantId: { type: "string" },
                  quantity: { type: "integer", minimum: 1 },
                  unitCost: { type: "integer", minimum: 0, description: "Private commercial field; staff roles only" },
                  receivedQuantity: { type: "integer", minimum: 0 },
                },
              },
            },
            evidenceIds: { type: "array", items: { type: "string" } },
            receipts: { type: "array", items: { type: "object" } },
            submittedAt: { type: ["string", "null"], format: "date-time" },
            approvedAt: { type: ["string", "null"], format: "date-time" },
            cancelledAt: { type: ["string", "null"], format: "date-time" },
            cancellationReason: { type: ["string", "null"] },
            closedAt: { type: ["string", "null"], format: "date-time" },
            closeReason: { type: ["string", "null"] },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        StockCount: {
          type: "object",
          additionalProperties: false,
          required: ["id", "variantId", "locationId", "expectedQuantity", "countedQuantity", "status", "countScope", "reason", "evidenceId", "discrepancyId", "createdAt"],
          properties: {
            id: { type: "string" },
            variantId: { type: "string" },
            locationId: { type: "string" },
            expectedQuantity: { type: "integer", minimum: 0 },
            countedQuantity: { type: "integer", minimum: 0 },
            status: { type: "string", enum: ["MATCHED", "DISCREPANCY", "RECONCILED"] },
            countScope: { type: "string", enum: ["VARIANT_GLOBAL", "SERIALIZED_LOCATION"] },
            reason: { type: "string" },
            evidenceId: { type: "string" },
            discrepancyId: { type: ["string", "null"] },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        StockDiscrepancy: {
          type: "object",
          additionalProperties: false,
          required: ["id", "stockCountId", "variantId", "locationId", "expectedQuantity", "countedQuantity", "variance", "status", "resolution", "resolutionReason", "resolutionEvidenceId", "resolvedAt", "createdAt"],
          properties: {
            id: { type: "string" },
            stockCountId: { type: "string" },
            variantId: { type: "string" },
            locationId: { type: "string" },
            expectedQuantity: { type: "integer", minimum: 0 },
            countedQuantity: { type: "integer", minimum: 0 },
            variance: { type: "integer" },
            status: { type: "string", enum: ["OPEN", "RESOLVED"] },
            resolution: { type: ["string", "null"], enum: ["ADJUST_STOCK", "ACCEPT_NO_CHANGE", null] },
            resolutionReason: { type: ["string", "null"] },
            resolutionEvidenceId: { type: ["string", "null"] },
            resolvedAt: { type: ["string", "null"], format: "date-time" },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        AuthError: {
          type: "object",
          required: ["success", "message", "errors"],
          additionalProperties: false,
          properties: {
            success: { type: "boolean", const: false },
            message: { type: "string" },
            errors: {
              type: "array",
              items: {
                type: "object",
                required: ["code", "message"],
                properties: {
                  code: {
                    type: "string",
                    example: "refresh_token_reuse_detected",
                  },
                  message: { type: "string" },
                },
              },
            },
          },
        },
        PublicQuoteTracking: {
          type: "object",
          additionalProperties: false,
          required: [
            "id",
            "version",
            "lineItems",
            "totalAmount",
            "estimatedDays",
            "status",
            "issuedAt",
            "expiresAt",
            "superseded",
            "depositRequirement",
            "paymentState",
          ],
          properties: {
            id: { type: "string" },
            version: { type: "integer", minimum: 1 },
            lineItems: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                required: ["description", "amount"],
                properties: {
                  description: { type: "string" },
                  amount: {
                    type: "integer",
                    minimum: 0,
                    description: "Minor currency units",
                  },
                },
              },
            },
            totalAmount: {
              type: "integer",
              minimum: 0,
              description: "Minor currency units",
            },
            estimatedDays: { type: "integer", minimum: 0 },
            status: {
              type: "string",
              enum: [
                "SENT",
                "VIEWED",
                "ACCEPTED",
                "DECLINED",
                "EXPIRED",
                "SUPERSEDED",
              ],
            },
            issuedAt: { type: "string", format: "date-time" },
            expiresAt: { type: "string", format: "date-time", nullable: true },
            superseded: { type: "boolean" },
            supersededByVersion: { type: ["integer", "null"], minimum: 1 },
            depositRequirement: {
              type: "object",
              additionalProperties: false,
              required: ["required", "amount", "currency", "dueBeforeWork"],
              properties: {
                required: { type: "boolean" },
                amount: { type: "integer", minimum: 0 },
                currency: { type: "string" },
                dueBeforeWork: { type: "boolean" },
              },
            },
            paymentState: {
              type: "object",
              additionalProperties: false,
              required: ["status", "confirmedAmount", "remainingAmount"],
              properties: {
                status: {
                  type: "string",
                  enum: [
                    "not_required",
                    "pending",
                    "partially_confirmed",
                    "confirmed",
                    "failed",
                  ],
                },
                confirmedAmount: { type: "integer", minimum: 0 },
                remainingAmount: { type: "integer", minimum: 0 },
              },
            },
          },
        },
        PublicRepairTracking: {
          type: "object",
          additionalProperties: false,
          required: ["id", "status", "nextAction", "updatedAt", "quote"],
          properties: {
            id: { type: "string" },
            status: { type: "string" },
            nextAction: { type: "string" },
            updatedAt: { type: "string", format: "date-time" },
            quote: {
              anyOf: [
                { $ref: "#/components/schemas/PublicQuoteTracking" },
                { type: "null" },
              ],
            },
          },
        },
        AccountSession: {
          type: "object",
          required: [
            "id",
            "createdAt",
            "lastUsedAt",
            "expiresAt",
            "deviceLabel",
            "current",
            "revoked",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string", format: "uuid" },
            createdAt: { type: "string", format: "date-time" },
            lastUsedAt: { type: "string", format: "date-time" },
            expiresAt: { type: "string", format: "date-time" },
            deviceLabel: {
              type: "string",
              description: "Bounded browser/device user-agent label",
            },
            current: { type: "boolean" },
            revoked: { type: "boolean" },
          },
        },
        EvidenceMetadata: {
          type: "object",
          description: "Safe evidence projection.",
          additionalProperties: false,
          required: [
            "id",
            "subjectType",
            "subjectId",
            "purpose",
            "displayName",
            "detectedMimeType",
            "size",
            "retentionState",
            "createdAt",
          ],
          properties: {
            id: { type: "string" },
            subjectType: {
              type: "string",
              enum: [
                "order",
                "repair",
                "claim",
                "return_request",
                "purchase_order",
              ],
            },
            subjectId: { type: "string" },
            purpose: {
              type: "string",
              enum: [
                "order_receipt",
                "repair_intake",
                "custody",
                "qc",
                "handover",
                "warranty",
                "return",
                "procurement",
              ],
            },
            displayName: { type: "string", maxLength: 160 },
            detectedMimeType: {
              type: "string",
              enum: ["image/jpeg", "image/png", "application/pdf"],
            },
            size: { type: "integer", minimum: 1, maximum: 5242880 },
            retentionState: {
              type: "string",
              enum: ["ACTIVE", "DELETE_PENDING", "DELETED", "LEGAL_HOLD"],
            },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        EvidenceDownload: {
          type: "object",
          additionalProperties: false,
          required: ["url", "expiresAt"],
          properties: {
            url: { type: "string", format: "uri" },
            expiresAt: { type: "string", format: "date-time" },
          },
        },
        FinancialDocument: {
          type: "object",
          description: "Immutable invoice or verified-payment receipt snapshot. Provider references and evidence storage keys are excluded.",
          additionalProperties: false,
          required: ["id", "documentNumber", "kind", "orderId", "currency", "issuedAt", "items", "subtotal", "tax", "shipping", "total", "paymentMethod"],
          properties: {
            id: { type: "string" },
            documentNumber: { type: "string" },
            kind: { type: "string", enum: ["INVOICE", "RECEIPT"] },
            orderId: { type: "string" },
            currency: { type: "string", pattern: "^[A-Z]{3}$" },
            issuedAt: { type: "string", format: "date-time" },
            items: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                required: ["name", "sku", "unitAmount", "quantity", "lineTotal"],
                properties: {
                  name: { type: "string" },
                  sku: { type: "string" },
                  unitAmount: { type: "integer", minimum: 0 },
                  quantity: { type: "integer", minimum: 1 },
                  lineTotal: { type: "integer", minimum: 0 },
                },
              },
            },
            subtotal: { type: "integer", minimum: 0 },
            tax: { type: "integer", minimum: 0 },
            shipping: { type: "integer", minimum: 0 },
            total: { type: "integer", minimum: 0 },
            paymentMethod: { type: "string", enum: ["paystack", "bank_transfer", "pay_on_pickup"] },
            paidAt: { type: "string", format: "date-time", nullable: true },
          },
        },
        WarrantyTerms: {
          type: "object",
          required: ["version", "terms"],
          additionalProperties: false,
          properties: {
            version: { type: "string" },
            terms: { type: "string" },
          },
        },
        Inspection: {
          type: "object",
          required: ["summary"],
          additionalProperties: false,
          properties: {
            summary: { type: "string" },
            inspectedAt: { type: "string", format: "date-time" },
            inspector: { type: "string" },
          },
        },
        ConditionEvidence: {
          type: "object",
          required: ["url"],
          additionalProperties: false,
          properties: {
            url: { type: "string", format: "uri" },
            alt: { type: "string" },
          },
        },
        CatalogueVariantInput: {
          type: "object",
          required: ["product", "sku", "attributes", "price", "condition"],
          properties: {
            product: { type: "string" },
            sku: { type: "string" },
            attributes: { type: "object" },
            price: { type: "number", minimum: 0 },
            condition: { type: "string" },
            inStock: { type: "number", minimum: 0 },
          },
        },

        CatalogueSearchQuery: {
          type: "object",
          properties: {
            q: {
              type: "string",
              description:
                "Text search across name, description, brand, and tags",
            },
            category: { type: "string" },
            brand: { type: "string" },
            condition: {
              type: "string",
              enum: ["new", "used_good", "refurbished_grade_a"],
            },
            availability: {
              type: "string",
              enum: ["in_stock", "low_stock", "out_of_stock", "sourcing"],
            },
            minPrice: { type: "integer", minimum: 0 },
            maxPrice: { type: "integer", minimum: 0 },
            sort: {
              type: "string",
              enum: ["price_asc", "price_desc", "newest", "relevance"],
            },
            page: { type: "integer", minimum: 1, default: 1 },
            limit: { type: "integer", minimum: 1, maximum: 100, default: 10 },
          },
        },
        PublicVariant: {
          type: "object",
          required: [
            "id",
            "sku",
            "attributes",
            "price",
            "condition",
            "availability",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            sku: { type: "string" },
            attributes: { type: "object" },
            price: { type: "number", minimum: 0 },
            condition: { type: "string" },
            availability: { type: "string" },
          },
        },
        PublicProduct: {
          type: "object",
          required: [
            "id",
            "name",
            "slug",
            "description",
            "category",
            "brand",
            "images",
            "variants",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            slug: { type: "string" },
            description: { type: "string" },
            category: { type: "string" },
            brand: { type: "string" },
            images: { type: "array", items: { type: "string" } },
            variants: {
              type: "array",
              items: { $ref: "#/components/schemas/PublicVariant" },
            },
          },
        },
        PublicationRequirement: {
          type: "object",
          required: ["code", "path", "message"],
          properties: {
            code: { type: "string" },
            path: { type: "string" },
            message: { type: "string" },
          },
        },
        PublicationError: {
          type: "object",
          required: ["success", "message", "errors"],
          properties: {
            success: { type: "boolean", const: false },
            message: { type: "string" },
            errors: {
              type: "array",
              items: { $ref: "#/components/schemas/PublicationRequirement" },
            },
          },
        },
        WarrantyEligibility: {
          type: "object",
          required: ["eligible", "reasonCode", "customerMessage"],
          additionalProperties: false,
          properties: {
            eligible: { type: "boolean" },
            reasonCode: { type: "string" },
            customerMessage: { type: "string" },
          },
        },
        Warranty: {
          type: "object",
          required: [
            "id",
            "sourceType",
            "sourceId",
            "status",
            "effectiveAt",
            "expiresAt",
            "termsVersion",
            "coverageSummary",
            "exclusions",
            "claimEligibility",
            "createdAt",
            "updatedAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            sourceType: { type: "string", enum: ["order", "repair"] },
            sourceId: { type: "string" },
            status: {
              type: "string",
              enum: ["active", "expired", "void", "upcoming", "exhausted"],
            },
            effectiveAt: { type: "string", format: "date-time" },
            expiresAt: { type: "string", format: "date-time" },
            termsVersion: { type: "string" },
            coverageSummary: { type: "string" },
            exclusions: { type: "array", items: { type: "string" } },
            claimEligibility: {
              $ref: "#/components/schemas/WarrantyEligibility",
            },
            remainingClaimAllowance: { type: ["integer", "null"] },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        ClaimInformationRequest: {
          type: "object",
          required: ["id", "message"],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            message: { type: "string" },
            dueAt: { type: ["string", "null"], format: "date-time" },
            fulfilledAt: { type: ["string", "null"], format: "date-time" },
          },
        },
        ClaimRemedy: {
          type: "object",
          required: ["type", "summary"],
          additionalProperties: false,
          properties: {
            type: {
              type: "string",
              enum: ["repair", "replacement", "refund", "store_credit"],
            },
            summary: { type: "string" },
            outcome: { type: ["string", "null"] },
          },
        },
        Claim: {
          type: "object",
          required: [
            "id",
            "warranty",
            "status",
            "description",
            "customerSafeTimeline",
            "createdAt",
            "updatedAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            warranty: {
              type: "object",
              required: ["id"],
              properties: { id: { type: "string" } },
            },
            status: { type: "string" },
            description: { type: "string" },
            customerSafeTimeline: {
              type: "array",
              items: {
                type: "object",
                required: ["status", "at"],
                properties: {
                  status: { type: "string" },
                  at: { type: "string", format: "date-time" },
                  message: { type: ["string", "null"] },
                },
              },
            },
            nextAction: { type: ["string", "null"] },
            informationRequests: {
              type: "array",
              items: { $ref: "#/components/schemas/ClaimInformationRequest" },
            },
            remedy: {
              type: ["object", "null"],
              $ref: "#/components/schemas/ClaimRemedy",
            },
            customerSafeReason: { type: ["string", "null"] },
            evidence: { type: "array", items: { type: "object" } },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        ReturnRefundSummary: {
          type: "object",
          required: ["status", "amount", "currency"],
          additionalProperties: false,
          properties: {
            status: { type: "string" },
            amount: { type: "integer", minimum: 0 },
            currency: { type: "string" },
            initiatedAt: { type: ["string", "null"], format: "date-time" },
            completedAt: { type: ["string", "null"], format: "date-time" },
            failureAction: { type: ["string", "null"] },
            customerReference: { type: ["string", "null"] },
          },
        },
        ReturnEligibility: {
          type: "object",
          required: [
            "eligible",
            "reasonCode",
            "customerMessage",
            "eligibleItems",
            "deadline",
            "availableRemedies",
          ],
          additionalProperties: false,
          properties: {
            eligible: { type: "boolean" },
            reasonCode: { type: "string" },
            customerMessage: { type: "string" },
            eligibleItems: {
              type: "array",
              items: {
                type: "object",
                required: ["variantSku", "quantity"],
                properties: {
                  variantSku: { type: "string" },
                  name: { type: "string" },
                  quantity: { type: "integer" },
                },
              },
            },
            deadline: { type: "string", format: "date-time" },
            availableRemedies: { type: "array", items: { type: "string" } },
            requirements: { type: "array", items: { type: "string" } },
          },
        },
        ReturnRequest: {
          type: "object",
          required: [
            "id",
            "orderId",
            "status",
            "items",
            "reason",
            "customerSafeTimeline",
            "createdAt",
            "updatedAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            orderId: { type: "string" },
            status: { type: "string" },
            remedy: { type: ["string", "null"] },
            items: {
              type: "array",
              items: {
                type: "object",
                required: ["variantSku", "quantity"],
                properties: {
                  variantSku: { type: "string" },
                  quantity: { type: "integer" },
                  acceptedQuantity: { type: "integer" },
                },
              },
            },
            reason: { type: "string" },
            customerSafeTimeline: { type: "array", items: { type: "object" } },
            nextAction: { type: ["string", "null"] },
            evidence: { type: "array", items: { type: "object" } },
            refund: { $ref: "#/components/schemas/ReturnRefundSummary" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        SupportMessage: {
          type: "object",
          required: ["id", "authorType", "body", "createdAt"],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            authorType: { type: "string", enum: ["customer", "support"] },
            body: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        SupportTicket: {
          type: "object",
          required: [
            "id",
            "subject",
            "category",
            "priority",
            "status",
            "conversation",
            "createdAt",
            "updatedAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            subject: { type: "string" },
            category: { type: "string" },
            priority: { type: "string" },
            status: { type: "string" },
            responseExpectation: { type: ["string", "null"] },
            customerSafeSla: { type: ["string", "null"] },
            linkedResource: { type: ["object", "null"] },
            nextAction: { type: ["string", "null"] },
            resolutionSummary: { type: ["string", "null"] },
            conversation: {
              type: "array",
              items: { $ref: "#/components/schemas/SupportMessage" },
            },
            evidence: { type: "array", items: { type: "object" } },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        Notification: {
          type: "object",
          required: [
            "id",
            "type",
            "title",
            "safePreview",
            "resourceType",
            "resourceId",
            "readAt",
            "createdAt",
            "mandatory",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            type: { type: "string" },
            title: { type: "string" },
            safePreview: { type: "string" },
            resourceType: { type: "string" },
            resourceId: { type: "string" },
            readAt: { type: ["string", "null"], format: "date-time" },
            createdAt: { type: "string", format: "date-time" },
            expiresAt: { type: ["string", "null"], format: "date-time" },
            mandatory: { type: "boolean" },
          },
        },
        NotificationPreferences: {
          type: "object",
          required: [
            "version",
            "mandatoryCategories",
            "optionalCategories",
            "channels",
          ],
          additionalProperties: false,
          properties: {
            version: { type: "string" },
            mandatoryCategories: { type: "array", items: { type: "string" } },
            optionalCategories: { type: "object" },
            channels: { type: "object" },
          },
        },
        GuidanceRecommendation: {
          type: "object",
          required: ["variant", "score", "factors", "availability"],
          additionalProperties: false,
          properties: {
            variant: { type: "string" },
            score: { type: "number" },
            factors: { type: "array", items: { type: "string" } },
            availability: { type: "string" },
          },
        },
        GuidanceSession: {
          type: "object",
          required: [
            "id",
            "rulesVersion",
            "evaluatedAt",
            "status",
            "recommendations",
            "createdAt",
            "updatedAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            budget: { type: ["integer", "null"] },
            useCase: { type: ["string", "null"] },
            brands: { type: "array", items: { type: "string" } },
            categories: { type: "array", items: { type: "string" } },
            requiredFeatures: { type: "array", items: { type: "string" } },
            requirementsSummary: { type: "object" },
            rulesVersion: { type: "string" },
            evaluatedAt: { type: "string", format: "date-time" },
            staleAt: { type: ["string", "null"], format: "date-time" },
            status: { type: "string" },
            recommendations: {
              type: "array",
              items: { $ref: "#/components/schemas/GuidanceRecommendation" },
            },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        GuidanceEscalation: {
          type: "object",
          required: ["id", "status", "question", "createdAt", "updatedAt"],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            status: { type: "string" },
            question: { type: "string" },
            response: { type: ["string", "null"] },
            advisorDisplayName: { type: ["string", "null"] },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        OrganisationMembership: {
          type: "object",
          additionalProperties: false,
          required: ["role", "status", "canPurchase"],
          properties: {
            role: { type: "string", enum: ["OWNER", "ADMIN", "BUYER", "VIEWER"] },
            status: { type: "string", enum: ["ACTIVE", "REVOKED"] },
            canPurchase: { type: "boolean" },
          },
        },
        Organisation: {
          type: "object",
          additionalProperties: false,
          required: ["id", "name", "type", "billingEmail", "status", "membership", "createdAt", "updatedAt"],
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            type: { type: "string", enum: ["business", "school", "nonprofit", "government", "other"] },
            billingEmail: { type: "string", format: "email" },
            status: { type: "string", enum: ["ACTIVE", "SUSPENDED", "CLOSED"] },
            membership: { $ref: "#/components/schemas/OrganisationMembership" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        B2BOrderProcurementSnapshot: {
          type: "object",
          additionalProperties: false,
          required: ["organisationId", "requestId", "quotationId", "quotationVersion", "lineItems", "subtotal", "tax", "fees", "fulfilmentCharge", "totalAmount", "currency", "termsVersion", "warrantySummary", "supportSummary", "validUntil", "approvedAt", "purchaseOrderReference"],
          properties: {
            organisationId: { type: "string" },
            requestId: { type: "string" },
            quotationId: { type: "string" },
            quotationVersion: { type: "integer", minimum: 1 },
            lineItems: {
              type: "array",
              items: {
                type: "object",
                additionalProperties: false,
                required: ["description", "quantity", "unitPrice", "totalAmount"],
                properties: {
                  description: { type: "string" },
                  quantity: { type: "integer", minimum: 1 },
                  unitPrice: { type: "integer", minimum: 0 },
                  totalAmount: { type: "integer", minimum: 0 },
                },
              },
            },
            subtotal: { type: "integer", minimum: 0 },
            tax: { type: "integer", minimum: 0 },
            fees: { type: "integer", minimum: 0 },
            fulfilmentCharge: { type: "integer", minimum: 0 },
            totalAmount: { type: "integer", minimum: 0 },
            currency: { type: "string", pattern: "^[A-Z]{3}$" },
            termsVersion: { type: "string" },
            warrantySummary: { type: ["string", "null"] },
            supportSummary: { type: ["string", "null"] },
            validUntil: { type: "string", format: "date-time" },
            approvedAt: { type: "string", format: "date-time" },
            purchaseOrderReference: { type: ["string", "null"] },
          },
        },
        ProcurementRequirement: {
          type: "object",
          required: [
            "id",
            "category",
            "quantity",
            "minimumSpecifications",
            "preferredCondition",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            category: { type: "string" },
            quantity: { type: "integer" },
            minimumSpecifications: { type: "string" },
            preferredCondition: { type: "string" },
            notes: { type: ["string", "null"] },
          },
        },
        ProcurementClarification: {
          type: "object",
          required: ["id", "question", "requestedAt"],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            question: { type: "string" },
            response: { type: ["string", "null"] },
            requestedAt: { type: "string", format: "date-time" },
            respondedAt: { type: ["string", "null"], format: "date-time" },
          },
        },
        ProcurementRequest: {
          type: "object",
          required: [
            "id",
            "organisationName",
            "organisationType",
            "contactName",
            "contactEmail",
            "contactPhone",
            "requirements",
            "status",
            "version",
            "createdAt",
            "updatedAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            organisationId: { type: ["string", "null"] },
            organisationName: { type: "string" },
            organisationType: { type: "string" },
            contactName: { type: "string" },
            contactEmail: { type: "string" },
            contactPhone: { type: "string" },
            requirements: {
              type: "array",
              items: { $ref: "#/components/schemas/ProcurementRequirement" },
            },
            budgetRange: {
              type: "object",
              properties: {
                minimum: { type: ["integer", "null"] },
                maximum: { type: ["integer", "null"] },
              },
            },
            requiredBy: { type: ["string", "null"], format: "date-time" },
            fulfilmentMode: { type: "string" },
            fulfilmentLocation: { type: ["string", "null"] },
            softwareAndLicensingNeeds: { type: ["string", "null"] },
            warrantyAndSupportNeeds: { type: ["string", "null"] },
            setupDeploymentNeeds: { type: ["string", "null"] },
            accessibilityNeeds: { type: ["string", "null"] },
            notes: { type: ["string", "null"] },
            status: { type: "string" },
            version: { type: "integer" },
            timeline: { type: "array", items: { type: "object" } },
            clarifications: {
              type: "array",
              items: { $ref: "#/components/schemas/ProcurementClarification" },
            },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        ProcurementQuotation: {
          type: "object",
          required: [
            "id",
            "requestId",
            "version",
            "lineItems",
            "subtotal",
            "tax",
            "fees",
            "fulfilmentCharge",
            "totalAmount",
            "currency",
            "validUntil",
            "termsVersion",
            "status",
            "superseded",
            "conversionStatus",
            "createdAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            requestId: { type: "string" },
            organisationId: { type: ["string", "null"] },
            version: { type: "integer" },
            lineItems: { type: "array", items: { type: "object" } },
            subtotal: { type: "integer" },
            tax: { type: "integer" },
            fees: { type: "integer" },
            fulfilmentCharge: { type: "integer" },
            totalAmount: { type: "integer" },
            currency: { type: "string" },
            validUntil: { type: "string", format: "date-time" },
            termsVersion: { type: "string" },
            warrantySummary: { type: ["string", "null"] },
            supportSummary: { type: ["string", "null"] },
            status: { type: "string" },
            superseded: { type: "boolean" },
            conversionStatus: { type: "string" },
            orderId: { type: ["string", "null"] },
            document: { type: ["object", "null"] },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        ServicePolicy: {
          type: "object",
          required: ["version", "source", "responsibilities", "exclusions"],
          additionalProperties: false,
          properties: {
            version: { type: "string" },
            source: { type: "string" },
            responsibilities: { type: "array", items: { type: "string" } },
            exclusions: { type: "array", items: { type: "string" } },
          },
        },
        ServiceAssessment: {
          type: "object",
          required: ["result"],
          additionalProperties: false,
          properties: {
            result: {
              type: "string",
              enum: ["COMPATIBLE", "PARTIALLY_COMPATIBLE", "INCOMPATIBLE"],
            },
            summary: { type: ["string", "null"] },
            assumptions: { type: "array", items: { type: "string" } },
            requirements: { type: "array", items: { type: "string" } },
            requiredParts: { type: "array", items: { type: "string" } },
            requiredSoftware: { type: "array", items: { type: "string" } },
            limitations: { type: "array", items: { type: "string" } },
            exclusions: { type: "array", items: { type: "string" } },
            customerResponsibilities: {
              type: "array",
              items: { type: "string" },
            },
            nextAction: { type: ["string", "null"] },
            assessedAt: { type: ["string", "null"], format: "date-time" },
          },
        },
        ServiceRequest: {
          type: "object",
          required: [
            "id",
            "serviceType",
            "device",
            "desiredOutcome",
            "dataMigrationRequired",
            "fulfilmentPreference",
            "responsibilityPolicyVersion",
            "status",
            "createdAt",
            "updatedAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            serviceType: { type: "string" },
            device: {
              type: "object",
              required: ["category"],
              properties: {
                category: { type: "string" },
                brand: { type: ["string", "null"] },
                model: { type: ["string", "null"] },
                currentSpecifications: { type: ["string", "null"] },
              },
            },
            desiredOutcome: { type: "string" },
            softwareRequirements: { type: ["string", "null"] },
            dataMigrationRequired: { type: "boolean" },
            fulfilmentPreference: { type: "string" },
            timeConstraints: { type: ["string", "null"] },
            notes: { type: ["string", "null"] },
            responsibilityPolicyVersion: { type: "string" },
            status: { type: "string" },
            timeline: { type: "array", items: { type: "object" } },
            assessment: {
              type: ["object", "null"],
              $ref: "#/components/schemas/ServiceAssessment",
            },
            evidence: { type: "array", items: { type: "object" } },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        ServiceQuotation: {
          type: "object",
          required: [
            "id",
            "serviceRequestId",
            "version",
            "lineItems",
            "totalAmount",
            "currency",
            "estimatedDays",
            "expiresAt",
            "status",
            "superseded",
            "createdAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            serviceRequestId: { type: "string" },
            version: { type: "integer" },
            lineItems: { type: "array", items: { type: "object" } },
            totalAmount: { type: "integer" },
            currency: { type: "string" },
            estimatedDays: { type: "integer" },
            expiresAt: { type: "string", format: "date-time" },
            status: { type: "string" },
            superseded: { type: "boolean" },
            depositRequirement: { type: "object" },
            paymentState: { type: "object" },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        ServiceHistory: {
          type: "object",
          required: [
            "id",
            "serviceReference",
            "serviceType",
            "deviceSafeLabel",
            "performedAt",
            "status",
            "workSummary",
            "createdAt",
            "updatedAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            serviceReference: { type: "string" },
            serviceType: { type: "string" },
            deviceSafeLabel: { type: "string" },
            performedAt: { type: "string", format: "date-time" },
            status: { type: "string" },
            workSummary: { type: "string" },
            customerVisiblePartsAndServices: {
              type: "array",
              items: { type: "string" },
            },
            warrantyOutcome: { type: ["string", "null"] },
            nextRecommendedMaintenance: { type: ["string", "null"] },
            authorizedDocuments: { type: "array", items: { type: "object" } },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        ServiceExecution: {
          type: "object",
          required: ["id", "serviceRequestId", "customer", "quotation", "assignedTechnicianId", "schedule", "deviceSafeLabel", "status", "version", "timestamps"],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            serviceRequestId: { type: "string" },
            customer: { type: "string", description: "Customer identifier; staff execution response only" },
            quotation: {
              type: "object",
              additionalProperties: false,
              required: ["id", "version", "totalAmount", "currency", "estimatedDays"],
              properties: {
                id: { type: "string" },
                version: { type: "integer" },
                totalAmount: { type: "integer" },
                currency: { type: "string" },
                estimatedDays: { type: "integer" },
              },
            },
            assignedTechnicianId: { type: "string" },
            schedule: {
              type: "object",
              additionalProperties: false,
              required: ["startAt", "endAt", "mode", "location"],
              properties: {
                startAt: { type: "string", format: "date-time" },
                endAt: { type: "string", format: "date-time" },
                mode: { type: "string", enum: ["onsite", "drop_off", "pickup", "remote"] },
                location: { type: ["string", "null"] },
              },
            },
            deviceSafeLabel: { type: "string" },
            status: { type: "string", enum: ["SCHEDULED", "IN_PROGRESS", "COMPLETED", "CANCELLED"] },
            version: { type: "integer" },
            timestamps: { type: "object" },
          },
        },
        MaintenancePlan: {
          type: "object",
          required: [
            "id",
            "scope",
            "frequency",
            "startDate",
            "renewalModel",
            "status",
            "price",
            "currency",
            "termsVersion",
            "cancellationInstructions",
            "createdAt",
            "updatedAt",
          ],
          additionalProperties: false,
          properties: {
            id: { type: "string" },
            scope: { type: "string" },
            coveredDevices: { type: "array", items: { type: "string" } },
            includedServices: { type: "array", items: { type: "string" } },
            frequency: { type: "string" },
            startDate: { type: "string", format: "date-time" },
            renewalDate: { type: ["string", "null"], format: "date-time" },
            renewalModel: { type: "string" },
            visitLimits: { type: ["string", "null"] },
            exclusions: { type: "array", items: { type: "string" } },
            status: { type: "string" },
            price: { type: "integer" },
            currency: { type: "string" },
            termsVersion: { type: "string" },
            cancellationInstructions: { type: "string" },
            version: { type: "integer" },
            cancellation: { type: ["object", "null"] },
            renewedFromId: { type: ["string", "null"] },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        MaintenancePlanAdmin: {
          allOf: [
            { $ref: "#/components/schemas/MaintenancePlan" },
            { type: "object", required: ["customerId", "version"], properties: { customerId: { type: "string" } } },
          ],
        },
      },
    },
  },
  apis: ["./src/routes/*.js"],
};

export const swaggerSpec = swaggerJSDoc(options);
